export const LX = {
  bg: '#0F1115',
  surface: '#181B22',
  surfaceElev: '#1F232C',
  surfaceAlt: '#242935',
  border: 'rgba(255,255,255,0.07)',
  borderStrong: 'rgba(255,255,255,0.14)',
  text: '#F4F5F8',
  textDim: '#9CA3B4',
  textMuted: '#5E6473',
  blue: '#5B8BFF',
  blueDeep: '#3A6AE6',
  blueGlow: 'rgba(91,139,255,0.25)',
  lime: '#B8F26A',
  limeDeep: '#86C73B',
  coral: '#FF6B6B',
  amber: '#FFB547',
  violet: '#C88CFF',
  cat: {
    adjectif: '#FFB547',
    verbe: '#5B8BFF',
    nom: '#B8F26A',
    adverbe: '#C88CFF',
    expression: '#FF6B6B',
  },
};

export const DAILY_SEQUENCE = [
  { type: 'truefalse', word: 'scintiller', def: "Briller d'un éclat vif et tremblant.", isCorrect: true },
  { type: 'multiple', word: 'sagace', correctIdx: 2, choices: [
    "Qui parle beaucoup et sans retenue.",
    "Qui agit sans réfléchir, impulsif.",
    "Qui a une intelligence vive, perspicace.",
    "Qui est très en colère.",
  ]},
  { type: 'fillblank',
    before: 'Un observateur ',
    after: ' aurait remarqué ce détail dans la foule.',
    choices: ['sagace', 'sempiternel', 'opiniâtre', 'ubuesque'],
    correctIdx: 0,
  },
  { type: 'match', pairs: [
    { word: 'flâner', def: 'Se promener sans but, en prenant son temps.' },
    { word: 'susurrer', def: "Murmurer doucement à l'oreille." },
    { word: 'scintiller', def: "Briller d'un éclat vif et tremblant." },
    { word: 'badinage', def: 'Échange de propos légers, plaisanterie douce.' },
  ]},
  { type: 'input', def: 'Qui ne peut être exprimé par des mots ; indicible.', answer: 'ineffable' },
];
